Initial commit
Assasinnys/basic-components-exercise pull request #1
Opened 2021-06-07 15:53 UTC by Valentin2508247

2021-06-07 20:55 UTC, Assasinnys requested changes
Check my comments and fix. Also, you need to merge my last commit in the master branch. it's a fix of the nasa photo description

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +
it's not a part of exercise. don't use view models if you don't know how it works. This code is not suitable for this project. For this task you need to write all code in the MainActivity class.

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +        }
it's violation of the MVVM architecture. Don't use architecture for this exercise.

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +    }
Use string resources instead of hardcoded strings

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/res/layout/main_activity.xml
> +        android:text=""
Useless

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/res/layout/main_activity.xml
> +        android:text="Load photo"
Use string resources instead of hardcoded strings

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/res/menu/main_menu.xml
> +    <!--        app:showAsAction="ifRoom"/>-->
Delete comments

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/viewModels/MainActivityViewModel.kt
> +}
You don't need the view model on this exercise.

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +//            }
Delete comments

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +//            menu?.findItem(R.id.action_date)?.title = it.date
Delete comments

2021-06-07 20:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +//        menu?.findItem(R.id.action_date)?.title = data.date
Delete comments

2021-06-08 19:02 UTC, Assasinnys submitted a review, later dismissed
![Screenshot_1623178584](https://user-images.githubusercontent.com/40615443/121241610-4dc6d480-c8a4-11eb-948e-f66858493f70.png)
The "Load button" covers photo description.
Why do you use the gray color? It would be better if you changed it, because the light theme is similar to the dark theme

2021-06-09 18:02 UTC, Valentin2508247 commented
Sometimes photos do not load. Can you help me to change api key?

2021-06-10 09:54 UTC, Assasinnys commented
You need to generate API Key here: https://api.nasa.gov/ . Then change "DEMO_KEY" to the your key. You can use search to find it.

2024-09-16 12:44 UTC, closed without merging