add: ui design
Assasinnys/basic-components-exercise pull request #2
Opened 2021-06-10 15:46 UTC by Aliibnabdul

2021-06-29 19:09 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +
Explain the reason of changing this.

2021-06-30 08:07 UTC, Aliibnabdul commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +
It need to reinit coroutineScope after cancel

2021-07-01 21:56 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +
Sure

2021-07-01 21:59 UTC, Assasinnys commented
If connection is lost, but user uploaded screen, he will see this bug.
![connection_bug](https://user-images.githubusercontent.com/40615443/124194141-b33b6900-dad0-11eb-8aa0-30888b9faddd.png)

2021-07-01 22:01 UTC, Assasinnys requested changes

2021-07-01 22:01 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +        ).show()
It's better to disable future dates. DatePicker can do this.

2021-07-04 21:17 UTC, Aliibnabdul commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +        ).show()
Ok, done.

2021-07-05 16:21 UTC, Assasinnys requested changes

2021-07-05 16:21 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +        datePickerDialog.show()
Good option is to use apply{} function

2021-07-05 16:21 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +                contentLayout.alphaFade(!b)
You could make it shorter

2021-07-06 13:04 UTC, Assasinnys requested changes
Looks good. Small details left.

2021-07-06 13:04 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
>      private fun showNetworkError(b: Boolean) {
Bad name of the parameter

2021-07-06 13:04 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
>  fun View.alphaFade(b: Boolean) {
Bad name of the parameter

2021-07-06 13:04 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
>          //TODO: handle request's errors here
Remove comments from your code except the doc comments

2021-07-08 17:11 UTC, Assasinnys requested changes

2021-07-08 17:11 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/ui/dailyimage/MainActivity.kt
> +    private fun showNetworkError(showError: Boolean) {
Ohh. Name of a boolean parameters should start with "is", "are", "has".

2021-07-21 11:02 UTC, Assasinnys requested changes
When daily is uploaded without an internet connection, the satellite overlaps nasa image. Also the satellite stays on the screen.
![Screenshot_1626739324](https://user-images.githubusercontent.com/40615443/126478719-892f6e1c-a2bc-4088-a78d-a5e6a5e3fa02.png)

2021-07-23 13:12 UTC, Assasinnys requested changes

2021-07-23 13:12 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
>      val end = if (b) 1F else 0F
Again. Boolean name is invalid

2021-08-07 09:41 UTC, Assasinnys requested changes

2021-08-07 09:41 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
> +    val end = if (show) 1F else 0F
It's wrong. Boolean variables a bit similar with english questions. They always starts like this: "isLoading", "hasLoaded", "areItemsSame"

2021-08-07 17:56 UTC, Aliibnabdul commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
> +    val end = if (show) 1F else 0F
In this case, the parameter is passed to the function "show" - true, hide - false. Show means the show command (показать). I don't know how to call it differently.

2021-08-07 18:52 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
> +    val end = if (show) 1F else 0F
It will be "isShowing"

2021-08-07 18:55 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
> +    val end = if (show) 1F else 0F
it's like a question. "Is showing? true/false". It helps you to read the code like a book :)

2021-08-07 19:09 UTC, Assasinnys commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
> +    val end = if (show) 1F else 0F
Hm. I've found explanation for you. Look, you have name of a variable and value. So, your var's name is a question, value is answer to this question. )

2021-08-11 08:49 UTC, Aliibnabdul commented on app/src/main/java/com/example/basiccomponents/extensions/ViewExt.kt
> +    val end = if (show) 1F else 0F
I agree that naming is very important, i am not a linguist, i may be wrong, but I think show is more suitable here: show? translates as "показать?"

2021-10-06 22:15 UTC, Assasinnys approved these changes

2021-10-06 22:15 UTC, merged